leftnav:
- identifier: a0732033-4dab-4beb-940a-076e7239b051
  name: MIT ELECTION DATA AND SCIENCE LAB
  pageRef: /external-resources/mit-election-data-and-science-lab_a0732033-4dab-4beb-940a-076e7239b051
  weight: 1000
